### ISSUE TITLE
outOfDate

### ISSUE THREAD

**Issue by anasty17** [jorgeajimenezl/aiomega#2]
i was trying to download folder in latest sdk version it have some new requirments and folder doesn't download, do u have an idea ?
cancel token is required but also i have failed to create one! i used '''MegaCancelToken_createInstance()'''
folders always fail to download on releases after 4.8.0

**Comment by jorgeajimenezl** [comment]
Hello @anasty17, that's because I haven't updated the project to that version of mega yet. I'm short of time now. Usually this only takes to change reference of the subrepository of mega here to the latest version, but I can be some issues to fix manually, so you can try. Let me know if works. I'll do it soon as possible. Thanks for your contribution

**Comment by anasty17** [comment]
> Hello @anasty17, that's because I haven't updated the project to that version of mega yet. I'm short of time now. Usually this only takes to change reference of the subrepository of mega here to the latest version, but I can be some issues to fix manually, so you can try. Let me know if works. I'll do it soon as possible. Thanks for your contribution

actually i'm not using ur project.
but i'm trying to find a solution
thanks in advance
